web:
    build: .
    ports:
     - "5000:5000"
    links:
     - consul1
consul1:
  image: "progrium/consul:latest"
  hostname: "consul1"
  ports:
    - "8400:8400"
    - "8500:8500"
    - "53:53"
  command: "-server -bootstrap-expect 3 -ui-dir /ui"
consul2:
  image: "progrium/consul:latest"
  hostname: "consul2"
  ports:
    - "8400"
    - "8500"
    - "8600"
  links:
    - "consul1:consul1"
    - web
  command: "-server -join consul1"
consul3:
  image: "progrium/consul:latest"
  hostname: "consul3"
  ports:
    - "8400"
    - "8500"
    - "8600"
  links:
    - "consul1:consul1"
    - web
  command: "-server -join consul1"
registrator:
  image: "gliderlabs/registrator"
  hostname: "registrator"
  volumes:
   - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - "consul1:consul1"
  command: "consul://consul1:8500"