web:
    image: kodjservice
    hostname: web
    ports:
     - "5000:5000"
    links:
     - consul1
consul1:
  image: "progrium/consul:latest"
  hostname: "consul1"
  ports:
    - "8400:8400"
    - "8500:8500"
    - "53:53"
  command: "-server -bootstrap-expect 1 -ui-dir /ui"
registrator:
  image: "gliderlabs/registrator"
  hostname: "registrator"
  volumes:
   - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - "consul1:consul1"
  command: "consul://consul1:8500"