service1:
    build: .
    hostname: service1
    ports:
     - "5000"
    links:
     - "consul1"
     - "registrator"
service2:
    build: .
    hostname: service2
    ports:
     - "5000"
    links:
     - "consul1"
     - "registrator"
consul1:
  image: "progrium/consul:latest"
  hostname: "consul"
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  command: "-server -bootstrap-expect 1 -ui-dir /ui"
registrator:
  image: "gliderlabs/registrator"
  hostname: "registrator"
  volumes:
   - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul1
  command: "-internal consul://consul1:8500"